### ISSUE TITLE
Data vs. File

### ISSUE THREAD

**Issue by DavidGagne** [agostini-tech/ATBGTransferDemo#1]
- [ ] I'm having a hard time understanding how to convert this implementation to deal with a simple JSON data request instead of a file transfer.
- [ ] I have a function that gets called to update Core Data based on a JSON endpoint. This function can be called from multiple places within the app -- _e.g._ at launch from within AppDelegate, by pulling down to refresh a UITableView in a ViewController -- so am not clear on where to declare the controller, which you have inside the ViewController class.

**Comment by dagostini** [comment]
Hi David,

1. You mean the data is being downloaded but you can't convert the JSON to the dictionary?
2. Your function is implemented in a class somewhere. Why not declare your controller there?

Sorry for the late reply, I just came back from a trip.

**Comment by DavidGagne** [comment]
Hello!
My first issue was about the difference between a dataTask and a downloadTask. Everywhere else in my code if I am using a URLSession to grab JSON, I just use a dataTask. But it seems like for URLSessionConfiguration.background connections you can only use downloadTask. That part I have handled.
My second issue is that my function is _not_ implemented in a class, and perhaps that is my problem. I have a simple functions.swift file with "standalone" functions. My fetchNewItems() function isn't in a class. Is that just crazy?

**Comment by dagostini** [comment]
Hey David,

When you say 'standalone' functions, do you mean class functions? Would it be possible to see some code, I could help you better if I can see the code you're referring to. You can always pull your function into a class and instantiate the class.

**Comment by DavidGagne** [comment]
Hi, Dejan,
No, my functions are not in a class at all. I just have a functions.swift file with a few functions in it that can be called from anywhere.
What's the best way to share some of my code? Just post it here? Email?

**Comment by dagostini** [comment]
Posting it here would be best, if you don't mind everyone seeing your implementation.

**Comment by DavidGagne** [comment]
I think I know what the problem is now. It's because I'm actually attempting to do the background transfer from a background fetch, and it might not even be required, based on the note at the top of this page: https://developer.apple.com/documentation/foundation/url_loading_system/downloading_files_in_the_background
It looks like I can just use a standard URLSession and don't need to worry about using a background one.

**Comment by DavidGagne** [comment]
Actually ... I think that note on the Apple Developer site is wrong. Any time I try to use a default URL session, like it says you can, I get a bunch of errors like "Lower protocol stack error" which, when I researched them last week, lead me to believe that you canNOT use a default URL session (which is what led me down this path to your code in the first place).

**Comment by dagostini** [comment]
If you're using the background fetch your app will only get a limited amount of execution time. Triggering your bg transfer from your bg fetch should work fine. In the delegate callback of your bg transfer you should be able to call your function that saves data to the database. Check if your delegate is getting called, you can use a simple trick: just post a local notification when the download is complete.

**Comment by DavidGagne** [comment]
Here's my background session class:

	class BackgroundSession: NSObject {
	    static let shared = BackgroundSession()
	    
	    static let identifier = Bundle.main.bundleIdentifier ?? "background.session"
	    
	    private var session: URLSession!
	    var backgroundTaskID: Int?
	    var stack: CoreDataStack?
	
	    var savedCompletionHandler: (() -> Void)?
	    
	    private override init() {
	        super.init()
	        
	        let configuration = URLSessionConfiguration.background(withIdentifier: BackgroundSession.identifier)
	        configuration.isDiscretionary = true
	        configuration.sessionSendsLaunchEvents = true
	        session = URLSession(configuration: configuration, delegate: self, delegateQueue: nil)
	    }
	
	    func start(_ request: URLRequest, stack: CoreDataStack) {
	        self.stack = stack
	        session.downloadTask(with: request).resume()
	    }
	}
	
	extension BackgroundSession: URLSessionDelegate {
	    func urlSessionDidFinishEvents(forBackgroundURLSession session: URLSession) {
	        DispatchQueue.main.async {
	            print( "urlSessionDidFinishEvents.forBackgroundURLSession" )
	            self.savedCompletionHandler?()
	            self.savedCompletionHandler = nil
	        }
	    }
	}
	
	extension BackgroundSession: URLSessionTaskDelegate {
	    func urlSession(_ session: URLSession, task: URLSessionTask, didCompleteWithError error: Error?) {
	        if let error = error {
	            // handle failure here
	            print("\(error.localizedDescription)")
	        }
	    }
	}
	
	extension BackgroundSession: URLSessionDownloadDelegate {
	    func urlSession(_ session: URLSession, downloadTask: URLSessionDownloadTask, didFinishDownloadingTo location: URL) {
	        do {
	            let data = try Data(contentsOf: location)
	            let json = JSON(parseJSON: String(data: data, encoding: .utf8)! )
	
	            print("got data!")
	            let jsonArray = json["items"].arrayValue
	            print( "Found \(jsonArray.count) items." )
	            processJSON(stack: self.stack!, json: json, isFirstRun: false, vc: nil, log_fetch: false)
	
	        } catch {
	            print("\(error.localizedDescription)")
	        }
	    }
	}
	
In AppDelegate, I have:
	
	    func application(_ application: UIApplication, handleEventsForBackgroundURLSession identifier: String, completionHandler: @escaping () -> Void) {
	        print( "AppDelegate.handleEventsForBackgroundURLSession" )
	        BackgroundSession.shared.savedCompletionHandler = completionHandler
	    }
	
	    func application(_ application: UIApplication,
	                     performFetchWithCompletionHandler completionHandler:
	        @escaping (UIBackgroundFetchResult) -> Void) {
	        print( "AppDelegate.performFetchWithCompletionHandler" )
	        let url = URL( string: recentAPI )!
	        var request = URLRequest(url: url, cachePolicy: .reloadIgnoringCacheData, timeoutInterval: 20)
	        request.httpMethod = "GET"
	        request.setValue("application/x-www-form-urlencoded", forHTTPHeaderField: "Content-Type")
	        BackgroundSession.shared.start(request, stack: self.coreDataStack)
	        completionHandler(.newData)
	    }
	
I hit Debug -> Simulate Background Fetch and everything executes as expected (including downloading the JSON) until it gets to my `processJSON` function -- which is not in any class and simply lives alone in a functions.swift file -- where everything stops at:
	
    stack.storeContainer.performBackgroundTask { context in ...}
	
until I click the app icon and bring it back to the foreground, at which point everything resumes from there.

**Comment by DavidGagne** [comment]
Here's processJSON:

	func processJSON(
	    stack: CoreDataStack,
	    json: JSON,
	    isFirstRun: Bool,
	    vc: ItemListViewController?,
	    log_fetch: Bool
	    ){
	
	    print( "entering processJSON()" )
	    let jsonDetailArray = json["detail"].arrayValue
	    let jsonArray = json["items"].arrayValue
	    
	    print( "Found \(jsonDetailArray.count) detail items." )
	    print( "Found \(jsonArray.count) items." )
	    
	    stack.mainContext.mergePolicy = NSMergeByPropertyObjectTrumpMergePolicy
	    stack.storeContainer.performBackgroundTask { context in
	        
	        for jsonDetailItem in jsonDetailArray {
	         ...
	        }
	        print( "finished detail items" )
	        
	        for jsonItem in jsonArray {
	         ...
	        }
	        print( "finished items" )
	        if ( log_fetch == true ){
	            logFetch()
	        }
	        DispatchQueue.main.async {
	            print( "About to finish processJSON backgroundCoreDataTask" )
	            if vc != nil{
	                vc?.update_segment()
	            }
	        }
	
	        print( "Finished processJSON backgroundCoreDataTask" )
	    }	
	}

**Comment by DavidGagne** [comment]
I should note that, yes, I understand that I'm not using _your_ background transfer class! So this isn't really your problem to solve in the least and I won't be offended if you tell me to buzz off. But -- in my defense -- there are only like two other people on the Internet apparently working on anything like this, so I reached out to you ...

**Comment by dagostini** [comment]
Hey David,

You're right, it's not my problem, but I'm always happy to help if I can, I certainly wouldn't tell you to buzz off :)

In your ```stack.container.performBackgroundTask { context in ...``` can you call ```beginBackgroundTask...``` so the system would give you extra execution time?

https://developer.apple.com/documentation/uikit/uiapplication/1623051-beginbackgroundtask

And don't forget to call the ```endBackgroundTask``` at the end :)

I believe this might solve your problem.

**Comment by DavidGagne** [comment]
I fear that something is causing the execution to choke as soon as it hits that line and the Core Data operation isn’t even starting, but I’ll certainly give it a shot.
Thanks!

**Comment by DavidGagne** [comment]
I added:

    var backgroundTaskID: UIBackgroundTaskIdentifier!
    backgroundTaskID = UIApplication.shared.beginBackgroundTask(withName: "Finish Core Data Tasks") {
        UIApplication.shared.endBackgroundTask( backgroundTaskID! )
        backgroundTaskID = UIBackgroundTaskInvalid
    }

just before this:

    stack.mainContext.mergePolicy = NSMergeByPropertyObjectTrumpMergePolicy

and then added:

    UIApplication.shared.endBackgroundTask( backgroundTaskID! )
    backgroundTaskID = UIBackgroundTaskInvalid

just after the close of this:

    stack.storeContainer.performBackgroundTask { context in

But it had no impact. I'm still seeing the same thing. The processJSON() executes the two print statements just before setting the mergePolicy and then everything stops until I return the app to the foreground, at which point execution continues.

**Comment by DavidGagne** [comment]
As a side note: When I execute processJSON using the "pull to refresh" on the UITableView -- _i.e._ using a shared.dataTask instead of the BackgroundSession() one -- the entire process completes nearly instantaneously, even on a slow network connection. I can't imagine that the problem here is that anything is taking too long.

**Comment by dagostini** [comment]
This code:

```
UIApplication.shared.endBackgroundTask( backgroundTaskID! )
backgroundTaskID = UIBackgroundTaskInvalid
```

will get executed before your closure even starts executing. Can you add this code just before

`DispatchQueue.main.async `

**Comment by DavidGagne** [comment]
Okay. I moved the code to end the backgroundTask to just before the call to DispatchQueue.main.async and it _kinda_ worked.
Now the process continues through to the DispatchQueue code, but not *consistently*. Sometimes it stops before checking whether vc is nil, for example. But no matter what, it doesn't continue to the end until / unless the app returns to the foreground.

(Really my goal here is simply to be able to set the applicationIconBadgeNumber based on the results of the background fetch; I can't fathom why this is so difficult. It seems like something that should be easy!)

**Comment by DavidGagne** [comment]
Hold the phone.

I moved the code:

            UIApplication.shared.endBackgroundTask( backgroundTaskID! )
            backgroundTaskID = UIBackgroundTaskInvalid

to be _inside_ the

        DispatchQueue.main.async { ... }

block (just after vc != nil block) and now it seems to be working correctly!

Testing more now, but I think that might have done it...

**Comment by DavidGagne** [comment]
**Yes!** It works!

Thank you _so_ much!

**Comment by dagostini** [comment]
No worries, I'm glad it worked :)

I was thinking that you don't want to execute that code that you're dispatching on the main queue, since it's updating the UI and your app is in the background anyway. But yeah, if you want it executed the code you wrote is great :)

Have a nice day David :)
Dejan.

**Comment by DavidGagne** [comment]
Well, like I said, the whole point of doing the background fetch is to update the `applicationIconBadgeNumber` when there's new data to show the user, so -- unless I'm wrong -- it _needs_ to be able to update the UI in order to do that.

So glad you helped me figure it out. *Thanks again, Dejan!*
